---
material-store:
  environment:
    stable:
      url: "https://materials.mr-beam.org"
      enabled: true
      healthcheck_url: "https://materials.mr-beam.org/healthcheck/app"
    prod:
      url: "https://materials.mr-beam.org"
      enabled: true
      healthcheck_url: "https://materials.mr-beam.org/healthcheck/app"
    beta:
      url: "https://materials.mr-beam.org"
      enabled: true
      healthcheck_url: "https://materials.mr-beam.org/healthcheck/app"
    alpha:
      url: "https://materials.mr-beam.org"
      enabled: true
      healthcheck_url: "https://materials.mr-beam.org/healthcheck/app"
    dev:
      url: "https://materials.mr-beam.org"
      enabled: true
      healthcheck_url: "https://materials.mr-beam.org/healthcheck/app"
