---
material-store:
  environment:
    stable:
      url: "https://material.store.mr-beam.org"
      enabled: false
      healthcheck_url: ""
    prod:
      url: "https://material.store.mr-beam.org"
      enabled: false
      healthcheck_url: ""
    beta:
      url: "https://material.store.mr-beam.org"
      enabled: false
      healthcheck_url: ""
    alpha:
      url: "https://material.store.mr-beam.org"
      enabled: false
      healthcheck_url: ""
    dev:
      url: "https://material-store-prod-cit5sagu3a-ew.a.run.app"
      enabled: true
      healthcheck_url: "https://material-store-prod-cit5sagu3a-ew.a.run.app/healthcheck/app"
